[toolchain]
anchor_version = "0.31.1"
solana_version = "2.2.12"

[features]
resolution = true
skip-lint = false

[programs.localnet]
twitter = "yuSXtGfd255QhTFq2HMRwwm6QEvJuz7LnHKqN5aTWZ2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
